name: push-pull

on: [push, pull_request]


jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: push
        run: echo "c'est un push"
  pull:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: pull
        run: echo "c'est une pull request"